### ISSUE TITLE
Error in json dump or parser.feed

### ISSUE THREAD

**Issue by qdiegoq** [chinoogawa/fbht#11]
Buenos Dias!
Uso:
FBHT 3.1 
Python2.7

Al querer Crear las cuentas en la opcion 1 me da:
"Error in json dump or parser.feed"
y Nada sucede...

El appID que cargo en este campo es de una APP que generé y habilite que esta vacía, esto es suficiente o me esta faltando algo? 

-Tema aparte, me gustaría conocer la idea que hay detrás del "New Like Flood" podría reproducirlo manualmente?. Desde ya gracias por tu tiempo! 

Gracias!

**Comment by aleperno** [comment]
Te pido algo de info:
- El resultado de ejecutar "pip freeze"
- Los logs (de haber algo al respecto)

No me fue posible reproducir el error.
