### ISSUE TITLE
how to setup and will  framework working ???

### ISSUE THREAD

**Issue by getD0w** [chinoogawa/fbht#12]
setup fbht by command : python3 setup.py . 
but failed

**Comment by aleperno** [comment]
Could you be more specific?
Please attach the console output.

**Comment by getD0w** [comment]
thanks you @aleperno  . I use missing  python3 setup.py  install and celebline server .

**Comment by getD0w** [comment]
can u demo function new flow like ?

**Comment by chinoogawa** [comment]
The vulnerability has been patched!
