### ISSUE TITLE
How can I install depences like Selenium, MyParser , etc?

### ISSUE THREAD

**Issue by edwardcp20** [chinoogawa/fbht#13]
How can I install depences like Selenium, MyParser , etc?, sorry but I am a beginner.
I downloaded python 2.7 but I don't know like install depences.

**Comment by aleperno** [comment]
Could you be a little more specific?
Which OS are you running? Which procedures have you tried?
If you have already installed pip, you should be able to install all dependencies doing
```pip install -r dependencias.txt```

**Comment by edwardcp20** [comment]
I have windows 7 and I have tried to install with setuptools.
