### ISSUE TITLE
Message: 'geckodriver.exe' executable needs to be in PATH

### ISSUE THREAD

**Issue by ziflar** [chinoogawa/fbht#14]
hi
i have run fbht on kali linux and i've got this error's : 

**- selenium.common.exceptions.WebDriverException: Message: 'geckodriver.exe' executable needs to be in PATH.** 

**- exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.firefox.service.Service object at 0x7f3682191c10>> ignored**

**My config is :** 

**firefox --version: Mozilla Firefox 50.0**

**selenium -version 3.0.1**

how to edit mainFunc.py to use geckodriver???

thank you for your help

**Comment by ziflar** [comment]
Nobody wants to answer me 
then I answer myself 
I've  edited the mainFunc.py file and I solved my problem
thx to myself

**Comment by ALiangLiang** [comment]
Maybe you can download [geckodriver.exe](https://github.com/mozilla/geckodriver/releases). And add geckodriver into PATH.
