### ISSUE TITLE
hello brother 

### ISSUE THREAD

**Issue by glerinsonum** [chinoogawa/fbht#15]
@chinoogawa hello brother. do you have any file.py example

get_number.py https://www.facebook.com/jim
get_location.py https://www.facebook.com/jim/photos/2332323442

thank

**Comment by ziflar** [comment]
get_email.py  https://www.facebook.com/jim. also needed

**Comment by illvart** [comment]
Nice tool, great work!

**Comment by glerinsonum** [comment]
@ziflar ? 
![1](https://cloud.githubusercontent.com/assets/21057103/24647701/8fde9802-18e6-11e7-8e3d-374cbfdbe9a4.jpg)

**Comment by ziflar** [comment]
@glerinsonum 
what help did you want??

**Comment by glerinsonum** [comment]
@ziflar 

What I can do I with those python scripts. 
First to open main.py or to install setup.py 
There no documentation ?

**Comment by glerinsonum** [comment]
@ziflar Hello brother of good. Tell me. How I can install or open your script. 
because python 2.7.3 does not have PIP

**Comment by freddy-sumba** [comment]
Hey guys, at 2 years ago, I was run this tool, and each time @chinoogawa  release some features to enhance this tool. Now I want to extract some content of user account such as likes and opened links to put in an algorithm of intelligence artificial to recommend content and for other way,  try to have some characteristic of personality. My question is: Considering some recents  changes of this tool and Facebook platform is possible use this tool to extract the content mentioned of an user?

**Comment by glerinsonum** [comment]
@f35 Hola Amigo, See this link. 
https://github.com/advenium/

**Comment by f35** [comment]
@glerinsonum, I was review https://github.com/advenium/ but I  need more information about this tools to will ejecute or understand it.

**Comment by glerinsonum** [comment]
@f35 You have need to contact with an web or app developer to help you with this contain.

**Comment by dzmaster** [comment]
hello brother i have to ask you somthing could you reply the instruction of how to install this app and how to use it ... if you want of course

**Comment by glerinsonum** [comment]
@ziflar How I can Integrate this python programming script into Maltego as Transform as module. Cordially thank you.

**Comment by glerinsonum** [comment]
@dzmaster

**Comment by glerinsonum** [comment]
@dzmaster

**Comment by glerinsonum** [comment]
@dzmaster download OpnOsnt https://ufile.io/s6c4d and share.

**Comment by glerinsonum** [comment]
@f35 Use Maltego CE. from Paterva.com
