### ISSUE TITLE
Problema ruta en linux

### ISSUE THREAD

**Issue by luisco** [chinoogawa/fbht#7]
Saludos Chino desde colombia,

Se me estaba presentando un error de rutas al generar "Bypass friendship privacy with graph support" y era por lo siguiente:

En el archivo mainFunc.py linea 1905 se encuentra la siguiente instrucción

![fbht](https://cloud.githubusercontent.com/assets/3302100/5594079/c70ebd34-9206-11e4-84a7-547780ff58b6.png)

Por favor cambiarla para los que usamos linux

![fbht_2](https://cloud.githubusercontent.com/assets/3302100/5594082/de884d72-9206-11e4-802e-e44a3bcd1a7f.png)

con eso se soluciona el problema al generar las gráficas

Excelente herramienta

**Comment by aleperno** [comment]
Si, quedó el error de mi merge de cuando se hizo multiplataforma, gracias por reportar!
