### ISSUE TITLE
elementary os (ubuntu) problem

### ISSUE THREAD

**Issue by SamirMahmudzade** [chinoogawa/fbht#8]
help please . i cant use ,write this error.
i use Elementary OS freya ( Ubuntu 14.04 )

/fbht# ./main.py
from: can't read /var/mail/mainFunc
from: can't read /var/mail/database
from: can't read /var/mail/time
from: can't read /var/mail/handlers
from: can't read /var/mail/sys
./main.py: line 9: globalLogin: command not found
./main.py: line 10: globalEmail: command not found
./main.py: line 11: globalPassword: command not found
./main.py: line 13: privacy: command not found
./main.py: line 14: privacySet: command not found
./main.py: line 16: syntax error near unexpected token `('
./main.py: line 16: `def main():'

**Comment by chinoogawa** [comment]
Can you tell me what python version are you using?
Also you should add this line #!/usr/bin/python at the begining of the main.py file

**Comment by f35** [comment]
Hi Nicolas, I have a problem when I want create users test, I was using python version 2.7.6. 
Problem:
Insert the amount of accounts for creation (4 min): 4
Error in json dump or parser.feed
Thanks

**Comment by chinoogawa** [comment]
Your Facebook language configuration must be in english :D probably that's the problem! 
The Like injection module isn't working anymore :S sorry about that! 
Let me know if the language solved your problem!
